# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
#  data_path: ./data/kinetics/test_data_joint.npy
  label_path: ./data/kinetics/test_label.pkl
  debug: False

# model
model: model.agcn.Model
model_args:
  num_class: 400
  num_person: 2
  num_point: 18
  graph: graph.kinetics.Graph
  graph_args:
    labeling_mode: 'spatial'


# test 
phase: test
device: 0
test_batch_size: 32
weights: ./runs/ki_agcn_joint-kinetics_50epochs.pt # ./runs/ki_agcn_joint-11-37500.pt  # ./pre_train/ki_agcn.pt
#weights: ./runs/ki_agcn_joint-11-37500.pt

work_dir: ./work_dir/kinetics/agcn_joint_test
model_saved_name: ./runs/ki_agcn_joint_test
save_score: True